import figt.PlayerStats;
import javax.swing.JOptionPane;

public class MainMenu extends javax.swing.JFrame
{
    PlayerStats stats = new PlayerStats();
    
    public MainMenu() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fightBtn = new javax.swing.JButton();
        huntBtn = new javax.swing.JButton();
        storeBtn = new javax.swing.JButton();
        titleScreenBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("Main Menu");
        jLabel1.setPreferredSize(new java.awt.Dimension(280, 60));

        fightBtn.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        fightBtn.setText("Fight !!!");
        fightBtn.setPreferredSize(new java.awt.Dimension(180, 50));
        fightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightBtnActionPerformed(evt);
            }
        });

        huntBtn.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        huntBtn.setText("Hunting");
        huntBtn.setPreferredSize(new java.awt.Dimension(180, 50));
        huntBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huntBtnActionPerformed(evt);
            }
        });

        storeBtn.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        storeBtn.setText("Store");
        storeBtn.setPreferredSize(new java.awt.Dimension(180, 50));
        storeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeBtnActionPerformed(evt);
            }
        });

        titleScreenBtn.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        titleScreenBtn.setText("Title Screen");
        titleScreenBtn.setPreferredSize(new java.awt.Dimension(180, 50));
        titleScreenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleScreenBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(huntBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(storeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleScreenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(fightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(huntBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(storeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(titleScreenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Fight Button
    private void fightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightBtnActionPerformed
        
        // Open the Fighting UI
        Fight fight = new Fight();
        fight.setVisible(true);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_fightBtnActionPerformed

    // Hunting Button
    private void huntBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huntBtnActionPerformed
        
        // Before showing the hunt UI, we need to check if the player
        // has the necessary item for hunting
        if (stats.hasHuntItem) 
        {
            // player can go hunt
            Hunting huntUi = new Hunting();
            huntUi.setVisible(true);
            
            this.setVisible(false);
        }else
        {
            JOptionPane.showMessageDialog(this, "You don't have any hunting items yet, \nyou can buy it at the store.");
        }
            
        
        
    }//GEN-LAST:event_huntBtnActionPerformed

    //Store Button
    private void storeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeBtnActionPerformed
       
        // Open Store GUI
        Store store = new Store();
        store.setVisible(true);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_storeBtnActionPerformed

    //Return to title screen button
    private void titleScreenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleScreenBtnActionPerformed
        // show the title screen
        TitleScreen titleScreen = new TitleScreen();
        titleScreen.setVisible(true);
        
        // Return to title screen
        this.setVisible(false);
        
    }//GEN-LAST:event_titleScreenBtnActionPerformed
    
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fightBtn;
    private javax.swing.JButton huntBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton storeBtn;
    private javax.swing.JButton titleScreenBtn;
    // End of variables declaration//GEN-END:variables
}
